version: "3.8"
services:
  backend:
    image: "mengyuzou/springboot-react-fullstack:28.5.2024.11.55.31"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
